sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t parhambrz/dockerreact -f Dockerfile.dev .

script:
  - docker run -e CI=true parhambrz/dockerreact npm run test
